# -*- coding: utf-8 -*-
"""practiceprgms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hFcKgebcZsySAwINaX2e5nvgBFVd2pA
"""

#palindrome
a = input()
b = a[::-1]
if a == b:
  print('palindrome')
else:
    print('not palindrome')

#factorial
a = int(input())
fact = 1
for i in range(1,a+1):
  fact*=i
print('factorial:',fact)



#largest number
a = int(input())
b = int(input())
print(max(a,b))

#armstrong
a = int(input())
t = a
b = len(str(t))
sum = 0
while t>0:
  d = t%10
  sum += d**b
  t = t//10
if(sum == a):
  print('armstrong')
else:
  print('not armstrong')

#celtofahr
c = float(input("enter temperature in celcius:"))

f = (c *9/5) + 32

print("fahrenheit =", f)

#prime number
for n in range(1,51):
 if n>1:
  for i in range(2,n):
    if n%i == 0:
     break
  else:
      print(n, end=" ")



#swap
a = input()
b = input()
temp = a
a = b
b = temp
print(a)
print(b)

#fibonacci
n = int(input())
sum = 0
a, b = 0, 1
for i in range(n):
  print(a, end="")
  a, b = b , a + b

#avg
a = int(input())
b = int(input())
c = int(input())
avg = (a+b+c)//3
print(avg)

#vowels using slice
a = "butterfly"
vowels = a[1] + a[4]
print(vowels)

#vowels without slice
text = input()
vowels = "aeiouAEIOU"
count = 0
for ch in text:
  if ch in vowels:
    count += 1
    print(ch)
print(count)

a = int(input())
b = int(input())

x = a
y = b

while y != 0:
    x, y = y, x % y

gcd = x
lcm = (a * b) // gcd

print("GCD =", gcd)
print("LCM =", lcm)

a = [3,17,29,7,65,92,]
print(max(a),min(a))

def add(a,b):
  return a +b
def sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
add(5,6)

n = 75
if (n>0):
  print("positive number")
elif("n<0"):
  print("negative number")
else:
  print(0)

n = int(input())
if n%4 == 0:
  print("leap year ")
else:
  print("normal")

a = int(input())
if a%2 == 0 :
  print("even")
else:
  print("odd")

a = input()
b = input()
if sorted(a) == sorted(b):
  print('anagram')
else:
  print('not anagram')

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="" )
  print()

a = int(input())
for i in range(1,a+1):
    print("*"*i)

a = int(input())
for i in range(a):
  print(" "*i+"*"*(a-i))

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)
for i in range(a-1,0,-1):
  print(" "*(a-i)+"* "*i)

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)

#first 3 largest numbers
a = [20,40,80,70,60,30]
largest = sorted(a, reverse=True)[:3]
print("numbers:", largest)

#anagram without using sorted
a = input()
b = input()
if(a==b,b==a):
  print("anagram")
else:
  print("not anagram")

#power of 2
import math
a = int(input())
if math.sqrt(a):
  print("power of 2")
else:
  print("not")

a =  input()
b = input()
c = 0

for i in range(len(a)):
  if a[i]!=b[i]:
    c+=1
  if c==1:
   print("yes")
else:
  print("no")

a = input()
l ="  "
for i in  range(len(a)):
  c =" "
  for j in range(i,len(l)):
    if a[j] not in c:
      c+=a[j]
    else:
      break
    if (len(c)>len(l)):
      l=c
    print(len(l))

n = int(input())
x = list(map(int,input().split()))
for i in range  (1,n):
   if(x[i]==0):
    d = x[i-1]+1
    print(d)
    break

st = input()
st1 = list(st.lower())
vowels = ['a', 'e', 'i', 'o', 'u']
vlist = []
r = 0
for i in st1:
    if i in vowels:
        vlist.append(i)
vlist.reverse()
for i in range(len(st1)):
    if st1[i] in vowels:
        st1[i] = vlist[r]
        r += 1
print("".join(st1))

s = input()
longest = ""
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1] and len(sub) > len(longest):
            longest = sub
print(len(longest))

class student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
      print("name:",self.name)
      print("age:",self.age)

obj = student("vish",3)
obj.display()

class father:
  def bike(self):
    print("father has a bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

class father:
  def property(self):
    print("father's property")
class son(father):
  pass
obj = son()
obj.property()

class animal:
  def sound(self):
    print("animal makes sound")

class bank:
  def __init__(self):
    self.balance = 5000
  def show_balance(self):
     print("balance:",self.balance)
obj = bank()
obj.show_balance()

class multiply:
  def product(self,a = None , b =None , c = None):
    if a and b and c:
      print("product=",a*b*c)
    elif a and b:
      print("product=", a*b)
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

n = int(input())
b = int(str(n)[::-1])
for i in range(2,b):
  if b%i == 0:
    print("not prime")
    break
else:
    print("prime")

#adam number
n= int(input())
sq = n ** 2
rev= int(str(n)[::-1])
sqrev= rev** 2
revsq = int(str(sq)[::-1])
if sqrev== revsq:
    print("Adam")
else:
    print("NOT Adam")

#circular prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
def is_circular_prime(n):
    s = str(n)
    for i in range(len(s)):
        r = int(s[i:] + s[:i])
        if not is_prime(r):
            return False
    return True
n = int(input())
if is_circular_prime(n):
    print("Circular Prime")
else:
    print("Not Circular Prime")



x = 5
y = 3
z = 2
result = x + y * z // y
print(result)

import os
os.environ['KAGGLE_USERNAME']='arihantsharmakk'
os.environ['KAGGLE_KEY'] = 'KGAT_088c38bd49e7d3fa79ddf517f2cd03bd'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip titanic.zip

import pandas as pd
df = pd.read_csv("titanic-dataset.zip")
df.head(10)

print(len(df))
print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

df.columns

df.drop

df.isnull().sum()

df["Age"].fillna(df["Age"].median(),inplace=True)
print(df[["Age"]].head(10))
print(df[["Age"]].isnull().sum())

df.drop_duplicates(inplace=True)
print(df)